# Generated by Django 5.2.3 on 2025-06-11 01:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("active_tables", models.IntegerField(default=0)),
                ("pending_orders", models.IntegerField(default=0)),
                ("low_stock_items", models.IntegerField(default=0)),
                ("staff_on_duty", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("SALES_SUMMARY", "Sales Summary"),
                            ("TOP_ITEMS", "Top Selling Items"),
                            ("INVENTORY_ALERTS", "Inventory Alerts"),
                            ("STAFF_SCHEDULE", "Staff Schedule"),
                            ("RECENT_ORDERS", "Recent Orders"),
                            ("DAILY_REVENUE", "Daily Revenue Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refresh_rate",
                    models.IntegerField(
                        choices=[
                            (300, "5 minutes"),
                            (600, "10 minutes"),
                            (1800, "30 minutes"),
                            (3600, "1 hour"),
                            (7200, "2 hours"),
                        ],
                        default=300,
                        help_text="Refresh interval in seconds",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserDashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[("GRID", "Grid Layout"), ("LIST", "List Layout")],
                        default="GRID",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserWidgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.userdashboardpreference",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboardwidget",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("user_preference", "widget")},
            },
        ),
        migrations.AddField(
            model_name="userdashboardpreference",
            name="widgets",
            field=models.ManyToManyField(
                through="dashboard.UserWidgetSettings", to="dashboard.dashboardwidget"
            ),
        ),
    ]
